services:
  - type: worker
    name: esp8266-tg-broker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
