services:
  - type: worker
    name: esp8266-tg-broker
    runtime: python3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
